service: visonic-v8-aws-iot
frameworkVersion: '2'

useDotenv: true
configValidationMode: error
plugins:
  - serverless-bundle
  - serverless-plugin-aws-alerts
  
provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  region: eu-west-2
  stage: production
  logRetentionInDays: 3
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "iot:UpdateThingShadow"
          Resource: 
            - "arn:aws:iot:eu-west-2:557195821817:thing/alarm_status"
            - "arn:aws:iot:eu-west-2:557195821817:thing/alarm_status/*"

  environment:
    hostname: ${env:hostname}
    app_id: ${env:app_id}
    user_code: ${env:user_code}
    panel_id: ${env:panel_id}
    email: ${env:email}
    password: ${env:password}
    aws_iot_endpoint: ${env:aws_iot_endpoint}

functions:
  change:
    handler: handler.change_state
    timeout: 30
    memorySize: 128
    reservedConcurrency: 5
    events:
      - iot:
          sql: "SELECT state.desired.state as set_state FROM '$aws/things/alarm_status/shadow/update/accepted' WHERE state.desired.state <> Null"
  cron:
    handler: handler.cron
    timeout: 60
    memorySize: 128
    reservedConcurrency: 5
    events:
      - schedule: rate(1 minute)

package:
  exclude:
    - test/**
    - .*
    - .*/**
    - coverage/**
    - Dockerfile
    - '*.md'
    - '*.pem'
    - LICENSE
    - package*
    - wallaby.js

custom:
  bundle:
    linting: false
    sourcemaps: false

  alerts:
    stages:
      - production
    topics:
      alarm:
        topic: visonic-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${env:email}
    alarms:
      - functionErrors
      - functionThrottles